name: marcinmann
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3495122888125479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7274633375927806
  lightness: 0.024612812092527747
  saturation: 0.9457185384817421
  rhythmicContrast: 0.9515869708266109
purpose: []
