name: marcinmann
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#4a4a4a'
    - '#7b7b7b'
    - '#f3f3f3'
    - '#a3a3a3'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
